// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace Projekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201003021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 50,
                            AdditionalInfo = "Stare Miasto",
                            BuildingNumber = "12",
                            City = "Kraków",
                            Room = "1",
                            Street = "ul. Floriańska"
                        },
                        new
                        {
                            Id = 51,
                            AdditionalInfo = "Blisko Wawelu",
                            BuildingNumber = "25",
                            City = "Kraków",
                            Room = "2",
                            Street = "ul. Grodzka"
                        },
                        new
                        {
                            Id = 52,
                            AdditionalInfo = "Wejście od podwórza",
                            BuildingNumber = "7",
                            City = "Kraków",
                            Room = "101",
                            Street = "ul. Długa"
                        },
                        new
                        {
                            Id = 53,
                            AdditionalInfo = "2 piętro",
                            BuildingNumber = "3A",
                            City = "Kraków",
                            Room = "Sala szkoleniowa",
                            Street = "ul. Karmelicka"
                        },
                        new
                        {
                            Id = 54,
                            AdditionalInfo = "Śródmieście",
                            BuildingNumber = "89",
                            City = "Warszawa",
                            Room = "A",
                            Street = "ul. Marszałkowska"
                        },
                        new
                        {
                            Id = 55,
                            AdditionalInfo = "Metro Centrum",
                            BuildingNumber = "15",
                            City = "Warszawa",
                            Room = "B",
                            Street = "ul. Świętokrzyska"
                        },
                        new
                        {
                            Id = 56,
                            AdditionalInfo = "Kamienica",
                            BuildingNumber = "44",
                            City = "Warszawa",
                            Room = "3",
                            Street = "ul. Mokotowska"
                        },
                        new
                        {
                            Id = 57,
                            AdditionalInfo = "Parking z tyłu",
                            BuildingNumber = "120",
                            City = "Warszawa",
                            Room = "Sala 2",
                            Street = "ul. Puławska"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Description = "Workshops focused on instrumental, vocal and rhythm skills.",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 1002,
                            Description = "Art and creative expression through various painting techniques.",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 1003,
                            Description = "Workshops for learning digital and analog photography.",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 1004,
                            Description = "Culinary workshops focused on practical cooking skills.",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 1005,
                            Description = "Creative hand-made crafting workshops: ceramics, sewing, DIY.",
                            Name = "Handcraft"
                        },
                        new
                        {
                            Id = 1006,
                            Description = "Workshops teaching digital illustration, design and graphic tools.",
                            Name = "Digital Art"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopCycleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopCycleId");

                    b.HasIndex("UserId", "WorkshopCycleId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            EnrolledAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 305,
                            WorkshopCycleId = 2100
                        },
                        new
                        {
                            Id = 1001,
                            EnrolledAt = new DateTime(2025, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 306,
                            WorkshopCycleId = 2100
                        },
                        new
                        {
                            Id = 1002,
                            EnrolledAt = new DateTime(2025, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 307,
                            WorkshopCycleId = 2102
                        },
                        new
                        {
                            Id = 1003,
                            EnrolledAt = new DateTime(2025, 8, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 308,
                            WorkshopCycleId = 2102
                        },
                        new
                        {
                            Id = 1004,
                            EnrolledAt = new DateTime(2025, 9, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 309,
                            WorkshopCycleId = 2104
                        },
                        new
                        {
                            Id = 1005,
                            EnrolledAt = new DateTime(2025, 10, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 310,
                            WorkshopCycleId = 2101
                        },
                        new
                        {
                            Id = 1006,
                            EnrolledAt = new DateTime(2025, 9, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 311,
                            WorkshopCycleId = 2101
                        },
                        new
                        {
                            Id = 1007,
                            EnrolledAt = new DateTime(2025, 9, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 312,
                            WorkshopCycleId = 2103
                        },
                        new
                        {
                            Id = 1008,
                            EnrolledAt = new DateTime(2025, 9, 26, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 313,
                            WorkshopCycleId = 2103
                        },
                        new
                        {
                            Id = 1009,
                            EnrolledAt = new DateTime(2025, 10, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 314,
                            WorkshopCycleId = 2105
                        },
                        new
                        {
                            Id = 1010,
                            EnrolledAt = new DateTime(2025, 9, 30, 13, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 315,
                            WorkshopCycleId = 2105
                        },
                        new
                        {
                            Id = 1011,
                            EnrolledAt = new DateTime(2025, 9, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 316,
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 1012,
                            EnrolledAt = new DateTime(2025, 9, 27, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 317,
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 1013,
                            EnrolledAt = new DateTime(2025, 9, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 318,
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 1014,
                            EnrolledAt = new DateTime(2025, 9, 23, 15, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 319,
                            WorkshopCycleId = 2106
                        });
                });

            modelBuilder.Entity("Projekt.Models.InstructorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.Property<int?>("WorkshopCycleId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkshopSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("WorkshopCycleId");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("WorkshopSessionId");

                    b.ToTable("InstructorAssignments", (string)null);
                });

            modelBuilder.Entity("Projekt.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Projekt.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            Amount = 190m,
                            CreatedAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1000,
                            Method = "BankTransfer",
                            PaidAt = new DateTime(2025, 9, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2001,
                            Amount = 190m,
                            CreatedAt = new DateTime(2025, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1001,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 9, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2002,
                            Amount = 150m,
                            CreatedAt = new DateTime(2025, 8, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1002,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 8, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2003,
                            Amount = 150m,
                            CreatedAt = new DateTime(2025, 8, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1003,
                            Method = "BankTransfer",
                            PaidAt = new DateTime(2025, 8, 19, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2004,
                            Amount = 130m,
                            CreatedAt = new DateTime(2025, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1004,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 10, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2005,
                            Amount = 190m,
                            CreatedAt = new DateTime(2025, 10, 3, 10, 30, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1005,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 10, 3, 10, 35, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2006,
                            Amount = 190m,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 30, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1006,
                            Method = "BankTransfer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2007,
                            Amount = 150m,
                            CreatedAt = new DateTime(2025, 9, 27, 12, 30, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1007,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 9, 27, 12, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2008,
                            Amount = 150m,
                            CreatedAt = new DateTime(2025, 9, 28, 12, 40, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1008,
                            Method = "BankTransfer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2009,
                            Amount = 130m,
                            CreatedAt = new DateTime(2025, 10, 6, 13, 15, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1009,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 10, 6, 13, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2010,
                            Amount = 130m,
                            CreatedAt = new DateTime(2025, 10, 2, 13, 45, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1010,
                            Method = "BankTransfer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2011,
                            Amount = 480m,
                            CreatedAt = new DateTime(2025, 9, 30, 14, 10, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1011,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 9, 30, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2012,
                            Amount = 480m,
                            CreatedAt = new DateTime(2025, 10, 4, 14, 45, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1012,
                            Method = "BankTransfer",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2013,
                            Amount = 480m,
                            CreatedAt = new DateTime(2025, 9, 25, 15, 5, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1013,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 9, 25, 15, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2014,
                            Amount = 480m,
                            CreatedAt = new DateTime(2025, 10, 7, 15, 40, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1014,
                            Method = "BankTransfer",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Projekt.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 3000,
                            Comment = "Excellent intro – very clear.",
                            CreatedAt = new DateTime(2025, 9, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            UserId = 305,
                            WorkshopId = 2000
                        },
                        new
                        {
                            Id = 3001,
                            Comment = "Good pacing and helpful examples.",
                            CreatedAt = new DateTime(2025, 9, 15, 12, 30, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            UserId = 306,
                            WorkshopId = 2000
                        },
                        new
                        {
                            Id = 3002,
                            Comment = "Loved the techniques segment!",
                            CreatedAt = new DateTime(2025, 8, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            UserId = 307,
                            WorkshopId = 2001
                        },
                        new
                        {
                            Id = 3003,
                            Comment = "Great instructor, learned a lot.",
                            CreatedAt = new DateTime(2025, 8, 25, 11, 30, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            UserId = 308,
                            WorkshopId = 2001
                        },
                        new
                        {
                            Id = 3004,
                            Comment = "Inspired to keep writing!",
                            CreatedAt = new DateTime(2025, 10, 10, 19, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            UserId = 309,
                            WorkshopId = 2002
                        });
                });

            modelBuilder.Entity("Projekt.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator with full privileges",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Workshop instructor role",
                            Name = "Instructor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Default participant role",
                            Name = "Participant"
                        });
                });

            modelBuilder.Entity("Projekt.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 300,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "PBKDF2$100000$poQqsmFoMEhyq+OZGQuqNA==$FiwCznvrzeIrygvrSsLKg+zeLOGzdEKBKX6yUF8Y9n4="
                        },
                        new
                        {
                            Id = 301,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emma.clark@example.com",
                            FirstName = "Emma",
                            LastName = "Clark",
                            PasswordHash = "PBKDF2$100000$fAOe6EvSktj3LeaKfMv9pw==$LPtdYos6cJWAqKJuK0qpYZP1pM5PEHeoq6Gn2XuSUPw="
                        },
                        new
                        {
                            Id = 302,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "liam.foster@example.com",
                            FirstName = "Liam",
                            LastName = "Foster",
                            PasswordHash = "PBKDF2$100000$z+YpPjGBQrRTSd4UIZ6+lA==$mRekrpKtMED54QIO56INeSLajvHMoac/Re+nja5LYWQ="
                        },
                        new
                        {
                            Id = 303,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "olivia.hayes@example.com",
                            FirstName = "Olivia",
                            LastName = "Hayes",
                            PasswordHash = "PBKDF2$100000$ylvZzdlqZCfEriNBug77nw==$bobbTivyLqtTFQXZ8Vjuo7RGOtuqag4gijd8zw6Sxhc="
                        },
                        new
                        {
                            Id = 304,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "noah.reed@example.com",
                            FirstName = "Noah",
                            LastName = "Reed",
                            PasswordHash = "PBKDF2$100000$WTQKYqe9CGyeKYLEjW957A==$gAxAq0iknJQndcWxxHWbmtgbG625X6nDBdmxUJzSpnY="
                        },
                        new
                        {
                            Id = 305,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ava.mitchell@example.com",
                            FirstName = "Ava",
                            LastName = "Mitchell",
                            PasswordHash = "PBKDF2$100000$zNb/+4lxTJA7Y+6CpjeweA==$EbOTxJiJ01YpivxP+ZJFVJP6b064lU860oSOoU+x4zc="
                        },
                        new
                        {
                            Id = 306,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mason.turner@example.com",
                            FirstName = "Mason",
                            LastName = "Turner",
                            PasswordHash = "PBKDF2$100000$uQlosHzi1jSZBBeh8SGRVg==$BbeuE7I9SU09FA2DwAHbqAiUC32XexWci7vN530FAik="
                        },
                        new
                        {
                            Id = 307,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sophia.bennett@example.com",
                            FirstName = "Sophia",
                            LastName = "Bennett",
                            PasswordHash = "PBKDF2$100000$YHhOqyuHP5yTlAs1329hRA==$3jSzZPErkTP8wh1nI6tZ5H5uPMntu1/bc+y9hQV/NDE="
                        },
                        new
                        {
                            Id = 308,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ethan.cole@example.com",
                            FirstName = "Ethan",
                            LastName = "Cole",
                            PasswordHash = "PBKDF2$100000$+c6oZxt/UqKV/LuM2cmdiQ==$Wk33XC+fBr1/TuGLMscFLj3yLznv0wjXtGPxjoljQkI="
                        },
                        new
                        {
                            Id = 309,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isabella.parker@example.com",
                            FirstName = "Isabella",
                            LastName = "Parker",
                            PasswordHash = "PBKDF2$100000$WwYUKxQWivlVeEpp2MgTCw==$b8YpfwdMDTwF6uLh+rxwUHQFuDl6DMW/xQsPschb+aI="
                        },
                        new
                        {
                            Id = 310,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "logan.murphy@example.com",
                            FirstName = "Logan",
                            LastName = "Murphy",
                            PasswordHash = "PBKDF2$100000$iKNWL4Dmgw78KfxRt2Mm+Q==$Mpw4sf0E7b04vdTTm4KqmeQj7s6JPZZpjP6bTzhaKdk="
                        },
                        new
                        {
                            Id = 311,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mia.hughes@example.com",
                            FirstName = "Mia",
                            LastName = "Hughes",
                            PasswordHash = "PBKDF2$100000$kds6vCJpoPtBhvdORCCtLw==$P4M8Recj+QJCL/b546nujZOfuJhwVG2LYhZiQphEXAU="
                        },
                        new
                        {
                            Id = 312,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jacob.ward@example.com",
                            FirstName = "Jacob",
                            LastName = "Ward",
                            PasswordHash = "PBKDF2$100000$zAb+TtfAv+s4i45F4CFzyw==$kMqeNB0NitU+RMzYuMMQ18heQzGtVO3gMYUMyITgbdg="
                        },
                        new
                        {
                            Id = 313,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlotte.price@example.com",
                            FirstName = "Charlotte",
                            LastName = "Price",
                            PasswordHash = "PBKDF2$100000$qGC2nS1na8YAFR6+PhOf3Q==$L2VucAp7KXva570Lz44EYnKQALsgUr4mcvovidN7i3c="
                        },
                        new
                        {
                            Id = 314,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elijah.russell@example.com",
                            FirstName = "Elijah",
                            LastName = "Russell",
                            PasswordHash = "PBKDF2$100000$7ZoCIzPV1oEm7CF4JwLNrg==$dIT9NiULxEKI4SyORAK8qLAMvL8RjQv/zIWTHiF0l2Q="
                        },
                        new
                        {
                            Id = 315,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "harper.griffin@example.com",
                            FirstName = "Harper",
                            LastName = "Griffin",
                            PasswordHash = "PBKDF2$100000$SODPiZpTyWC2FqDKpFou4w==$7fSn0l6apniyLYFjOo3fVupPPFux3d4Ed02zanVbnsw="
                        },
                        new
                        {
                            Id = 316,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daniel.sanders@example.com",
                            FirstName = "Daniel",
                            LastName = "Sanders",
                            PasswordHash = "PBKDF2$100000$kkb2f/XcdUIq2ZBtN2Swng==$R4cVoFytT4hKJ8tyGo+nSLGFh0BsuqVFsbiyPqQmKGs="
                        },
                        new
                        {
                            Id = 317,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amelia.ross@example.com",
                            FirstName = "Amelia",
                            LastName = "Ross",
                            PasswordHash = "PBKDF2$100000$YK+Qlrn8jnvTG8fBR5W9MQ==$CBN5CAQ8kwpHgMAMxdLF0Jc1VredqBm8ar9tUDxoZgc="
                        },
                        new
                        {
                            Id = 318,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.peterson@example.com",
                            FirstName = "Henry",
                            LastName = "Peterson",
                            PasswordHash = "PBKDF2$100000$F1Td4JoTj5AKzT/gjLkYQQ==$PPkFBHwRJU1bqyeDi/elTucLjysoTs26QCaEw14Vfos="
                        },
                        new
                        {
                            Id = 319,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.howard@example.com",
                            FirstName = "Grace",
                            LastName = "Howard",
                            PasswordHash = "PBKDF2$100000$EU5HceSFyP1HzwfSw93WoQ==$uHxqGP27JiJY8Ruaqf822TuZkEr7PPJTeIko3jS2uBM="
                        });
                });

            modelBuilder.Entity("Projekt.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 300,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 301,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 302,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 303,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 304,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 305,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 306,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 307,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 308,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 309,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 310,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 311,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 312,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 313,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 314,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 315,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 316,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 317,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 318,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 319,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Projekt.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultInstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultInstructorId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            AddressId = 52,
                            AverageRating = 4.50m,
                            CategoryId = 1003,
                            DefaultInstructorId = 301,
                            Description = "A beginner-friendly workshop that introduces participants to the core foundations of photography, guiding them through essential camera settings, framing and composition techniques, and practical approaches to natural and artificial lighting, all aimed at helping them develop control, confidence, and a more intentional creative eye behind the lens.",
                            ImageUrl = "/workshop-images/photography_basics.jpg",
                            IsSeries = false,
                            MaxParticipants = 12,
                            Price = 190m,
                            ThumbnailUrl = "/workshop-images/photography_basics.jpg",
                            Title = "Photography Basics"
                        },
                        new
                        {
                            Id = 2001,
                            AddressId = 55,
                            AverageRating = 4.50m,
                            CategoryId = 1002,
                            DefaultInstructorId = 302,
                            Description = "A focused beginner program that guides students through four progressive weekly sessions, introducing essential chords, rhythm techniques, and foundational playing skills while building confidence and musical fluency in a supportive, hands-on environment.",
                            ImageUrl = "/workshop-images/acrylic_painting.jpg",
                            IsSeries = false,
                            MaxParticipants = 14,
                            Price = 150m,
                            ThumbnailUrl = "/workshop-images/acrylic_painting.jpg",
                            Title = "Acrylic Painting"
                        },
                        new
                        {
                            Id = 2002,
                            AddressId = 51,
                            AverageRating = 5.00m,
                            CategoryId = 1006,
                            DefaultInstructorId = 303,
                            Description = "A guided workshop that helps participants develop a distinctive narrative voice, create vivid and believable characters, and craft natural, engaging dialogue through focused exercises that inspire experimentation and strengthen overall storytelling skills.",
                            ImageUrl = "/workshop-images/creative_writing.jpg",
                            IsSeries = false,
                            MaxParticipants = 16,
                            Price = 130m,
                            ThumbnailUrl = "/workshop-images/creative_writing.jpg",
                            Title = "Creative Writing"
                        },
                        new
                        {
                            Id = 2003,
                            AddressId = 50,
                            CategoryId = 1001,
                            DefaultInstructorId = 301,
                            Description = "A focused beginner program that guides students through four progressive weekly sessions, introducing essential chords, rhythm techniques, and foundational playing skills while building confidence and musical fluency in a supportive, hands-on environment.",
                            ImageUrl = "/workshop-images/guitar_course.jpg",
                            IsSeries = true,
                            MaxParticipants = 14,
                            Price = 480m,
                            ThumbnailUrl = "/workshop-images/guitar_course.jpg",
                            Title = "4-Week Guitar Course"
                        });
                });

            modelBuilder.Entity("Projekt.Models.WorkshopCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstructorOverrideId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpenForEnrollment")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxParticipantsOverride")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("InstructorOverrideId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopCycles");

                    b.HasData(
                        new
                        {
                            Id = 2100,
                            DisplayName = "Photography Basics – Sept 10 2025",
                            EndDate = new DateTime(2025, 9, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = false,
                            StartDate = new DateTime(2025, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2000
                        },
                        new
                        {
                            Id = 2101,
                            DisplayName = "Photography Basics – Dec 15 2025",
                            EndDate = new DateTime(2025, 12, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = true,
                            StartDate = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2000
                        },
                        new
                        {
                            Id = 2102,
                            DisplayName = "Acrylic Painting – Aug 20 2025",
                            EndDate = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = false,
                            StartDate = new DateTime(2025, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2001
                        },
                        new
                        {
                            Id = 2103,
                            DisplayName = "Acrylic Painting – Jan 18 2026",
                            EndDate = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = true,
                            StartDate = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2001
                        },
                        new
                        {
                            Id = 2104,
                            DisplayName = "Creative Writing – Oct 5 2025",
                            EndDate = new DateTime(2025, 10, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = false,
                            StartDate = new DateTime(2025, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2002
                        },
                        new
                        {
                            Id = 2105,
                            DisplayName = "Creative Writing – Feb 10 2026",
                            EndDate = new DateTime(2026, 2, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = true,
                            StartDate = new DateTime(2026, 2, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2002
                        },
                        new
                        {
                            Id = 2106,
                            DisplayName = "4-Week Guitar Course – March 2026",
                            EndDate = new DateTime(2026, 3, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsOpenForEnrollment = true,
                            StartDate = new DateTime(2026, 3, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            WorkshopId = 2003
                        });
                });

            modelBuilder.Entity("Projekt.Models.WorkshopSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopCycleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("WorkshopCycleId");

                    b.ToTable("WorkshopSessions");

                    b.HasData(
                        new
                        {
                            Id = 2200,
                            AddressId = 52,
                            EndTime = new DateTime(2025, 9, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Photography Basics – Core Session",
                            WorkshopCycleId = 2100
                        },
                        new
                        {
                            Id = 2201,
                            AddressId = 52,
                            EndTime = new DateTime(2025, 12, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Photography Basics – Core Session",
                            WorkshopCycleId = 2101
                        },
                        new
                        {
                            Id = 2202,
                            AddressId = 55,
                            EndTime = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Acrylic Painting – Techniques Session",
                            WorkshopCycleId = 2102
                        },
                        new
                        {
                            Id = 2203,
                            AddressId = 55,
                            EndTime = new DateTime(2026, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Acrylic Painting – Techniques Session",
                            WorkshopCycleId = 2103
                        },
                        new
                        {
                            Id = 2204,
                            AddressId = 51,
                            EndTime = new DateTime(2025, 10, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 10, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Creative Writing – Narrative Fundamentals",
                            WorkshopCycleId = 2104
                        },
                        new
                        {
                            Id = 2205,
                            AddressId = 51,
                            EndTime = new DateTime(2026, 2, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 2, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Creative Writing – Narrative Fundamentals",
                            WorkshopCycleId = 2105
                        },
                        new
                        {
                            Id = 2206,
                            AddressId = 50,
                            EndTime = new DateTime(2026, 3, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 3, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Guitar Basics",
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 2207,
                            AddressId = 50,
                            EndTime = new DateTime(2026, 3, 11, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 3, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Chords & Rhythm",
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 2208,
                            AddressId = 50,
                            EndTime = new DateTime(2026, 3, 18, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 3, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Strumming Patterns & Dynamics",
                            WorkshopCycleId = 2106
                        },
                        new
                        {
                            Id = 2209,
                            AddressId = 50,
                            EndTime = new DateTime(2026, 3, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2026, 3, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            Topic = "Song Playthrough & Review",
                            WorkshopCycleId = 2106
                        });
                });

            modelBuilder.Entity("Projekt.Models.Enrollment", b =>
                {
                    b.HasOne("Projekt.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.WorkshopCycle", "WorkshopCycle")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkshopCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkshopCycle");
                });

            modelBuilder.Entity("Projekt.Models.InstructorAssignment", b =>
                {
                    b.HasOne("Projekt.Models.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projekt.Models.WorkshopCycle", null)
                        .WithMany("Instructors")
                        .HasForeignKey("WorkshopCycleId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Projekt.Models.Log", b =>
                {
                    b.HasOne("Projekt.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projekt.Models.Payment", b =>
                {
                    b.HasOne("Projekt.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Projekt.Models.Review", b =>
                {
                    b.HasOne("Projekt.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Workshop", "Workshop")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Projekt.Models.UserRole", b =>
                {
                    b.HasOne("Projekt.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projekt.Models.Workshop", b =>
                {
                    b.HasOne("Projekt.Models.Address", "Address")
                        .WithMany("Workshops")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.Category", "Category")
                        .WithMany("Workshops")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Models.User", "DefaultInstructor")
                        .WithMany()
                        .HasForeignKey("DefaultInstructorId");

                    b.Navigation("Address");

                    b.Navigation("Category");

                    b.Navigation("DefaultInstructor");
                });

            modelBuilder.Entity("Projekt.Models.WorkshopCycle", b =>
                {
                    b.HasOne("Projekt.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projekt.Models.User", "InstructorOverride")
                        .WithMany()
                        .HasForeignKey("InstructorOverrideId");

                    b.HasOne("Projekt.Models.Workshop", "Workshop")
                        .WithMany("Cycles")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("InstructorOverride");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Projekt.Models.WorkshopSession", b =>
                {
                    b.HasOne("Projekt.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projekt.Models.WorkshopCycle", "WorkshopCycle")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkshopCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("WorkshopCycle");
                });

            modelBuilder.Entity("Projekt.Models.Address", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Projekt.Models.Category", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Projekt.Models.Enrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Projekt.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Projekt.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Logs");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Projekt.Models.Workshop", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Projekt.Models.WorkshopCycle", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Instructors");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
